/**
 * pda_library_loader.js
 * Specialized library loader for Pushdown Automata.
 */

import { animatePdaDrawing } from './pda_animation.js';
import { addLogMessage, customAlert } from './utils.js';

const LIB_URL = './pda_library.json'; // Generated by GitHub Action

let libraryData = [];

/**
 * Fetches the PDA library and initializes the UI.
 */
/**
 * Fetches the PDA library and initializes search/filter/refresh listeners.
 */
export async function initializePdaLibrary() {
    const refreshBtn = document.getElementById('pdaLibRefresh');
    const searchInput = document.getElementById('pdaLibSearch');
    const filterSelect = document.getElementById('pdaLibFilter'); // New filter listener
    
    if (refreshBtn) refreshBtn.onclick = fetchLibrary;
    
    if (searchInput) {
        searchInput.oninput = () => {
            renderLibraryItems(searchInput.value.trim().toLowerCase());
        };
    }

    // ADDED: Re-filter the list whenever the Mode dropdown changes
    if (filterSelect) {
        filterSelect.onchange = () => {
            const query = searchInput ? searchInput.value.trim().toLowerCase() : "";
            renderLibraryItems(query);
        };
    }

    await fetchLibrary();
}

async function fetchLibrary() {
    const listEl = document.getElementById('pdaLibraryList');
    if (!listEl) return;
    
    listEl.innerHTML = '<div class="library-message">Syncing with GitHub Library...</div>';

    try {
        const response = await fetch(LIB_URL);
        if (!response.ok) throw new Error("Library file not found.");
        
        const rawData = await response.json();

        // THE FIX: Ensure libraryData is ALWAYS an array
        // If it's a single object, wrap it in []. If it's already an array, keep it.
        libraryData = Array.isArray(rawData) ? rawData : [rawData];
        
        renderLibraryItems("");
    } catch (e) {
        console.error("Library Load Error:", e);
        listEl.innerHTML = '<div class="library-message error">Failed to load pda_library.json</div>';
        // Initialize as empty array so search doesn't crash later
        libraryData = []; 
    }
}

/**
 * renderLibraryItems
 * Filters the library data based on both the text search query and 
 * the selected machine mode (NPDA/DPDA).
 */
function renderLibraryItems(query) {
    const listEl = document.getElementById('pdaLibraryList');
    const filterEl = document.getElementById('pdaLibFilter'); // Get the dropdown filter element
    if (!listEl) return;
    
    listEl.innerHTML = '';
    const filterValue = filterEl ? filterEl.value : 'all';

    const filtered = libraryData.filter(entry => {
        const machineData = entry.machine || entry;
        const machineType = (machineData.type || 'PDA').toUpperCase(); // Default to generic PDA if undefined
        
        // 1. Filter by Mode (DPDA/NPDA)
        // Logic: Show if 'all' is selected, if types match exactly, or if the machine 
        // is labeled as generic 'PDA' (making it visible in both specific filters).
        const matchesType = (filterValue === 'all') || 
                            (machineType === filterValue) || 
                            (machineType === 'PDA');
        
        // 2. Filter by Search Text
        const hay = `${entry.title} ${entry.description} ${entry.id}`.toLowerCase();
        const matchesSearch = hay.includes(query);

        return matchesType && matchesSearch;
    });

    if (filtered.length === 0) {
        listEl.innerHTML = `
            <div class="library-message" style="text-align:center; padding:20px; color:var(--muted); font-size:0.9em;">
                No matching PDA designs found.
            </div>`;
        return;
    }

    // Populate the list with the filtered results
    filtered.forEach(entry => {
        const el = createLibraryEntryEl(entry);
        listEl.appendChild(el);
    });
}

function createLibraryEntryEl(entry) {
    const container = document.createElement('div');
    container.className = 'library-entry';
    container.style.padding = "10px";
    container.style.borderBottom = "1px solid #e2e8f0";

    const machineData = entry.machine || entry;
    const isDPDA = machineData.type === 'DPDA';

    container.innerHTML = `
        <div style="display:flex; justify-content:space-between; align-items:start; margin-bottom:5px;">
            <div>
                <strong style="font-size:0.9em;">${entry.title || entry.id}</strong>
                <span class="library-entry-type" style="font-size:0.75em; color:var(--muted);">[${machineData.type}]</span>
            </div>
            <button class="icon-btn load-lib-btn" style="padding:4px 8px; font-size:0.8em;">
                <i data-lucide="play-circle"></i> Open
            </button>
        </div>
        <p style="font-size:0.8em; margin:0; color:#4a5568;">${entry.description || 'No description.'}</p>
    `;

    const openBtn = container.querySelector('.load-lib-btn');
    openBtn.onclick = async () => {
        addLogMessage(`Loading <strong>${entry.title}</strong> from library...`, 'library');
        
        // Update the Mode Dropdown in the UI to match the library entry
        const modeSelect = document.getElementById('pdaModeSelect');
        if (modeSelect) modeSelect.value = machineData.type;

        // Start the animated drawing
        await animatePdaDrawing(machineData);
        
        customAlert("Library Load Complete", `${entry.title} is now active.`);
    };

    if (window.lucide) lucide.createIcons({ nodes: [container] });
    return container;
}